name: tc_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24
  - pandas=2.0
  - scipy=1.10
  - matplotlib=3.7
  - geopandas=0.14
  - xarray=2023.6
  - pip
  - pip:
    - geopy>=2.4